name: Docker image build for uncommon cpu arch

on:
  push:
    branches: [ main, dev, docker ]
  pull_request:
    branches: [ main, dev, docker ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIM_VERSION: "1.6.0"
      DIVE_VERSION: "0.10.0"

    steps:
    - 
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - 
      name: Checkout nim version
      run: |
            set -euo pipefail
            cd nim
            git fetch --tags
            git checkout -f v${NIM_VERSION} --

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Docker Login
      timeout-minutes: 1
      if: success() && ${{ github.repository_owner }} == "maxisoft"
      run: |
            echo '${{ secrets.DOCKERIO_PASSWORD }}' | docker login --username "maxisoft" --password-stdin

    - name: Build And Push MultiArch images
      if: success() && ${{ github.repository_owner }} == "maxisoft"
      timeout-minutes: 360
      run: |
            set -euo pipefail
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker buildx build \
            --platform=linux/arm/v6,linux/ppc64le \
            --output "type=image,push=true" \
            --build-arg RUN_NIM_TEST=0 \
            --file ./Dockerfile . \
            --tag maxisoft/nim:uncommon_latest \
            --tag maxisoft/nim:uncommon_v${NIM_VERSION} \
            --tag ghcr.io/${{ github.repository_owner }}/nim-docker-images/nim:uncommon_latest \
            --tag ghcr.io/${{ github.repository_owner }}/nim-docker-images/nim:uncommon_v${NIM_VERSION}
