name: Docker image build

on:
  push:
    branches: [ main, dev, docker ]
  pull_request:
    branches: [ main, dev, docker ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIM_VERSION: "1.6.0"
      DIVE_VERSION: "0.10.0"

    steps:
    - 
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - 
      name: Checkout nim version
      run: |
            set -euo pipefail
            cd nim
            git fetch --tags
            git checkout -f v${NIM_VERSION} --

    - 
      name: Build Dockerfile
      timeout-minutes: 20
      run: |
            docker build -t nim_testing -t ghcr.io/${{ github.repository_owner }}/nim-docker-images/nim:x64 -f ./Dockerfile --build-arg RUN_NIM_TEST=1 .
    - 
      name: Install and Run Dive
      timeout-minutes: 2
      run: |
            set -euo pipefail
            pushd /tmp
            wget --no-verbose https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb
            sudo apt install --quiet -y ./dive_${DIVE_VERSION}_linux_amd64.deb
            popd
            CI=true dive --ci-config "${{ github.workspace }}/.dive-ci" nim_testing
            
    -
      name: Push x64 to ghcr
      if: success() && ${{ github.repository_owner }} == "maxisoft"
      run: |
            set -euo pipefail
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker push ghcr.io/${{ github.repository_owner }}/nim-docker-images/nim:x64

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Docker Login
      timeout-minutes: 1
      if: success() && ${{ github.repository_owner }} == "maxisoft"
      run: |
            echo '${{ secrets.DOCKERIO_PASSWORD }}' | docker login --username "maxisoft" --password-stdin

    - name: Build And Push MultiArch images
      if: success() && ${{ github.repository_owner }} == "maxisoft"
      timeout-minutes: 360
      run: |
            set -euo pipefail
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker buildx build \
            --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 \
            --output "type=image,push=true" \
            --build-arg RUN_NIM_TEST=0 \
            --file ./Dockerfile . \
            --tag maxisoft/nim:latest \
            --tag maxisoft/nim:v${NIM_VERSION} \
            --tag ghcr.io/${{ github.repository_owner }}/nim-docker-images/nim:latest \
            --tag ghcr.io/${{ github.repository_owner }}/nim-docker-images/nim:v${NIM_VERSION}
